export const NotFoundErrors = {
  USER: "User not found",
  TRANSACTION: "Transaction not found",
  TRANSACTIONS: "Transactions not found",
  CATEGORY: "Category not found",
  CATEGORIES: "Categories not found",
  SUBCATEGORY: "Subcategory not found",
  SUBCATEGORIES: "Subcategories not found",
  OTP: "OTP not found! Try again",
  REPORT: "Report not found",
  REPORTS: "Reports not found",
  COMMENT: "Comment not found",
  COMMENTS: "Comments not found",
  POST: "Post not found",
  POSTS: "Posts not found",
  MESSAGE: "Message not found",
  MESSAGES: "Messages not found",
  FEEDBACKS: "Feedbacks not found",
  CONVERSATION: "Conversation not found",
  CONVERSATIONS: "Conversations not found",
};
